### ISSUE TITLE
Data interface not showing in i3-wm and cinnamon

### ISSUE THREAD

**Issue by timomulder** [ros-simulation/stage_ros#17]
When I load stage_ros with my world file in i3-wm or cinnamon (on linux mint 17.1) it doesn't show the lasers or location of the robot (on-click). There is no way of doing this. It does show when I start the simulator in a XFCE session, that made me a bit more sure that it is a problem between stage and certain window managers. I have an Intel HD 4400 video chip with drivers installed. I hope it is not too hard to fix, maybe somebody has already a solution? Thanks in advance.

**Comment by wjwwood** [comment]
This looks to be a problem with stage itself, please file an issue on their tracker, thanks!

https://github.com/rtv/Stage/issues
