### ISSUE TITLE
Screenshots of stage not saved with roslaunch

### ISSUE THREAD

**Issue by quattrinili** [ros-simulation/stage_ros#23]
It seems that stage_ros (indigo) does not save the screenshots in the current folder (although the output says so) when stage_ros is launched through a launch file (while with rosrun works).

**Comment by wjwwood** [comment]
When run though a launch file the working directory is set to somewhere within the `ROS_HOME`, which by default is in `~/.ros`. You can look for the file there. See: http://answers.ros.org/question/57075/how-to-save-file-to-the-current-directory-with-roslaunch/
