### ISSUE TITLE
Lunar release

### ISSUE THREAD

**Issue by mikaelarguedas** [ros-simulation/stage_ros#44]
Hi `stage_ros` maintainers!

As you may know the next ROS release Lunar Loggerhead is around the corner :tada:

All dependencies of `stage_ros` are now released into Lunar! Please consider making a Lunar release soon, `stage_ros` is part of desktop_full, it is a requirement for the release of ROS Lunar.

Thanks!

**Comment by mikaelarguedas** [comment]
@rtv any update on this ? This repository is [one of the last missing](http://repositories.ros.org/status_page/blocked_releases_lunar.html?q=id%3D%22metapackages%22&s=6&r=1) for the Lunar release.

**Comment by rtv** [comment]
Working on this tonight. Will report back properly when I've reviewed what is/needs done.

**Comment by mikaelarguedas** [comment]
Hi @rtv,
Sorry to bother you again, do you have an update on this ? this package is now [the only one](http://repositories.ros.org/status_page/blocked_releases_lunar.html?q=id%3D%22metapackages%22&s=6&r=1) blocking the release of ROS Lunar. It would be really great to have this out for the [beta-testing phase starting on May 1st](https://discourse.ros.org/t/lunar-beta-testing-starting-on-monday-may-1st/1757)

**Comment by rtv** [comment]
Will have it ready for packaging/releasing by tomorrow night. (30 April). This has taken waaaay longer than I anticipated. Learning curve is mighty steep.

**Comment by mikaelarguedas** [comment]
that's awesome, thanks @rtv !
If you learned lessons that are not `stage_ros` specific and can benefit all maintainers, please consider submitting changes to http://wiki.ros.org/MaintenanceGuide. We tried to improve it recently but could use feedback from the community to help flatten the learning curve for all maintainers.

Regarding the release process you can find useful information [here](http://wiki.ros.org/bloom/Tutorials/ReleasingForANewROSDistro)

**Comment by rtv** [comment]
stage_ros changes are done. Am coordinating with @wjwwood on pushing to GitHun and the release process.

**Comment by rtv** [comment]
I applied my changes to my fork rtv/stage_ros, and created a PR for the upstream. Hopefully William can do the pull and make the release. I don't want to mess something up and thereby slow things down. Thanks @mikaelarguedas for the info.

**Comment by mikaelarguedas** [comment]
Thanks @rtv for the release! everything built fine :tada: . Closing this
